name: CI

on:
  push:
    branches: '*'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  0 */1 * * *

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Cache Depend on UNIX
      if: ${{ runner.os != 'Windows' }}
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
 
    - name: Get npm cache directory
      if: ${{ runner.os == 'Windows' }}
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    
    - name: Cache Depend on Windows
      if: ${{ runner.os == 'Windows' }}
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
      
    - name: Initializer ENV
      run: |
        npm install -g vsce
        npm install -g yarn
        yarn
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm test
    - name: Packing
      run: vsce package
