name: VSCE Publish

on:
  push:
    tags: 
      - 'v**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g vsce
    - run: npm install -g yarn
    - run: yarn
    - run: yarn build
    - run: vsce package --no-yarn
      env:
        CI: true
    - name: Publish to VSCode Marketplace
      uses: lannonbr/vsce-action@master
      with:
        args: "publish -p $VSCE_TOKEN --no-yarn"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

    - name: Publish to Open-VSX
      run: |
        npx ovsx publish -p ${{ secrets.OVSX_ACCESS_KEY }} --no-yarn
